server:
  port: 8091

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 0

sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: zhhhandsome1

dubbo:
  application:
    name: stick-upload-service
  protocol:
    name: dubbo
    port: 20891
  registry:
    address: nacos://${NACOS_HOST:localhost}:8848
    parameters:
      namespace: dev
      group: TOTAL_GROUP

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
