server:
  port: 8090

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 0

dubbo:
  application:
    name: stick-search-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${NACOS_HOST:localhost}:8848
    parameters:
      namespace: dev
      group: TOTAL_GROUP

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
